import './_styles/index.scss'

import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import Navbar from '@/layout/Navbar'

import Hamburguer from '@/components/Hamburguer'

import Providers from '@/contexts/Providers'

const inter = Inter({ subsets: ['latin'], weight: ["100", "200", "400", "600", "500", "700", "900"], variable: "--font-fugaz-one" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Hamburguer />
          {children}
        </Providers>
      </body>
    </html>
  )
}
