import './globals.css'

import type { Metadata } from 'next'

import { Fugaz_One, Inter } from 'next/font/google'

import Navbar from '@/layout/Navbar'

const fugazOne = Fugaz_One({ subsets: ['latin'], weight: ['400'] })
const inter = Inter({ subsets: ['latin'], weight: ["100", "200", "400", "600", "500", "700"], variable: "--font-fugaz-one" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fugazOne.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  )
}
