version: '3'

services:
  # # mongodb:
  # next-app:
  #   container_name: next-app
  #   image: next-app-image
  #   build: 
  #     # context: ./next-app
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - 3000:3000
  #   restart: always
  backend:
    image: paketobuildpacks/run
    ports: 
      - 8080:8080
