version: '3'

services:
  # mongodb:
  next-app:
    container_name: next-app
    image: next-js-app
    build: 
      context: ./next-app
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
  # backend:
