version: '3'

services:
  mongodb:

  next-app:
    container_name: next-app
    build: 
      context: ./next-app
      dockerfile: dev.Dockerfile
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:app/public
    networks:
      - my_network
    ports:
      - 3000:3000
      

  backend:

networks:
  my_network:
    external: true